/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.testing_uas;


import java.awt.Color;
import java.awt.CardLayout;


import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author FA506
 */
public class HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public HomeAdmin() {
        initComponents();

        jPanelMainAdmin.setLayout(new CardLayout());

        showDasboard();

        // mouse listener change color
        jPanelDasboardAdmin.setBackground(new Color(0,0,102));
        jPanelDasboardAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelDasboardAdmin.setBackground(new Color(153,153,255));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelDasboardAdmin.setBackground(new Color(0,0,102));
            }
        });
        jPanelCustomerAdmin.setBackground(new Color(0,0,102));
        jPanelCustomerAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustomerAdmin.setBackground(new Color(153,153,255));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustomerAdmin.setBackground(new Color(0,0,102));
            }
        });
        jPanelUserAdmin.setBackground(new Color(0,0,102));
        jPanelUserAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelUserAdmin.setBackground(new Color(153,153,255));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelUserAdmin.setBackground(new Color(0,0,102));
            }
        });
        jPanelServiceAdmin.setBackground(new Color(0,0,102));
        jPanelServiceAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelServiceAdmin.setBackground(new Color(153,153,255));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelServiceAdmin.setBackground(new Color(0,0,102));
            }
        });
        jPanelTransaksiAdmin.setBackground(new Color(0,0,102));
        jPanelTransaksiAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelTransaksiAdmin.setBackground(new Color(153,153,255));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelTransaksiAdmin.setBackground(new Color(0,0,102));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelDasboardAdmin = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanelCustomerAdmin = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanelUserAdmin = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanelServiceAdmin = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanelTransaksiAdmin = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jLabelrole = new javax.swing.JLabel();
        jPanelHsLogout1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelMainAdmin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jPanel7.setBackground(new java.awt.Color(0, 0, 102));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("TopService");

        jPanelDasboardAdmin.setBackground(new java.awt.Color(0, 0, 102));
        jPanelDasboardAdmin.setForeground(new java.awt.Color(153, 153, 255));
        jPanelDasboardAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDasboardAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelDasboardAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelDasboardAdminMouseExited(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(153, 153, 255));
        jLabel12.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setText("Dasboard");

        javax.swing.GroupLayout jPanelDasboardAdminLayout = new javax.swing.GroupLayout(jPanelDasboardAdmin);
        jPanelDasboardAdmin.setLayout(jPanelDasboardAdminLayout);
        jPanelDasboardAdminLayout.setHorizontalGroup(
            jPanelDasboardAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDasboardAdminLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel12)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanelDasboardAdminLayout.setVerticalGroup(
            jPanelDasboardAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDasboardAdminLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelCustomerAdmin.setBackground(new java.awt.Color(0, 0, 102));
        jPanelCustomerAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustomerAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCustomerAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCustomerAdminMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 255));
        jLabel13.setText("Customer");

        javax.swing.GroupLayout jPanelCustomerAdminLayout = new javax.swing.GroupLayout(jPanelCustomerAdmin);
        jPanelCustomerAdmin.setLayout(jPanelCustomerAdminLayout);
        jPanelCustomerAdminLayout.setHorizontalGroup(
            jPanelCustomerAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerAdminLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCustomerAdminLayout.setVerticalGroup(
            jPanelCustomerAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerAdminLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelUserAdmin.setBackground(new java.awt.Color(0, 0, 102));
        jPanelUserAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelUserAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelUserAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelUserAdminMouseExited(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 102));
        jLabel14.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 255));
        jLabel14.setText("User");

        javax.swing.GroupLayout jPanelUserAdminLayout = new javax.swing.GroupLayout(jPanelUserAdmin);
        jPanelUserAdmin.setLayout(jPanelUserAdminLayout);
        jPanelUserAdminLayout.setHorizontalGroup(
            jPanelUserAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserAdminLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUserAdminLayout.setVerticalGroup(
            jPanelUserAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserAdminLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelServiceAdmin.setBackground(new java.awt.Color(0, 0, 102));
        jPanelServiceAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelServiceAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelServiceAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelServiceAdminMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 255));
        jLabel15.setText("Service");

        javax.swing.GroupLayout jPanelServiceAdminLayout = new javax.swing.GroupLayout(jPanelServiceAdmin);
        jPanelServiceAdmin.setLayout(jPanelServiceAdminLayout);
        jPanelServiceAdminLayout.setHorizontalGroup(
            jPanelServiceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServiceAdminLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelServiceAdminLayout.setVerticalGroup(
            jPanelServiceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServiceAdminLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelTransaksiAdmin.setBackground(new java.awt.Color(0, 0, 102));
        jPanelTransaksiAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTransaksiAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelTransaksiAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelTransaksiAdminMouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 255));
        jLabel16.setText("Transaksi");

        javax.swing.GroupLayout jPanelTransaksiAdminLayout = new javax.swing.GroupLayout(jPanelTransaksiAdmin);
        jPanelTransaksiAdmin.setLayout(jPanelTransaksiAdminLayout);
        jPanelTransaksiAdminLayout.setHorizontalGroup(
            jPanelTransaksiAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransaksiAdminLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTransaksiAdminLayout.setVerticalGroup(
            jPanelTransaksiAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransaksiAdminLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hallo");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Role");

        jLabelNama.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNama.setText("jLabel3");

        jLabelrole.setForeground(new java.awt.Color(255, 255, 255));
        jLabelrole.setText("jLabel4");

        jPanelHsLogout1.setBackground(new java.awt.Color(0, 0, 102));
        jPanelHsLogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelHsLogout1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelHsLogout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelHsLogout1MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Logout -");

        javax.swing.GroupLayout jPanelHsLogout1Layout = new javax.swing.GroupLayout(jPanelHsLogout1);
        jPanelHsLogout1.setLayout(jPanelHsLogout1Layout);
        jPanelHsLogout1Layout.setHorizontalGroup(
            jPanelHsLogout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHsLogout1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelHsLogout1Layout.setVerticalGroup(
            jPanelHsLogout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHsLogout1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelCustomerAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDasboardAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelUserAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelServiceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelTransaksiAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel11))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelrole, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanelHsLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelrole))
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addGap(90, 90, 90)
                .addComponent(jPanelDasboardAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCustomerAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelUserAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelServiceAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTransaksiAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jPanelHsLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jPanelMainAdmin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelMainAdminLayout = new javax.swing.GroupLayout(jPanelMainAdmin);
        jPanelMainAdmin.setLayout(jPanelMainAdminLayout);
        jPanelMainAdminLayout.setHorizontalGroup(
            jPanelMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
        );
        jPanelMainAdminLayout.setVerticalGroup(
            jPanelMainAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelMainAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMainAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int id_user;
    private String nama, role;
    public void DataDiterima(int id_user,String nama, String role){
        this.id_user = id_user;
        this.nama = nama;
        this.role = role;
        jLabelNama.setText(nama);
        jLabelrole.setText(role);
    }
    private void showDasboard(){
        jPanelMainAdmin.removeAll();
        jPanelMainAdmin.repaint();
        jPanelMainAdmin.revalidate();
        
        jPanelMainAdmin.add(new PanelHome());
        jPanelMainAdmin.repaint();
        jPanelMainAdmin.revalidate();
    }

    private void jPanelDasboardAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDasboardAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelDasboardAdminMouseExited

    private void jPanelDasboardAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDasboardAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelDasboardAdminMouseEntered

    private void jPanelCustomerAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustomerAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelCustomerAdminMouseEntered

    private void jPanelCustomerAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustomerAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelCustomerAdminMouseExited

    private void jPanelUserAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelUserAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelUserAdminMouseEntered

    private void jPanelUserAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelUserAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelUserAdminMouseExited

    private void jPanelServiceAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelServiceAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelServiceAdminMouseEntered

    private void jPanelServiceAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelServiceAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelServiceAdminMouseExited

    private void jPanelTransaksiAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTransaksiAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelTransaksiAdminMouseExited

    private void jPanelTransaksiAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTransaksiAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelTransaksiAdminMouseEntered

    private void jPanelDasboardAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDasboardAdminMouseClicked
        // TODO add your handling code here:

        showDasboard();
    }//GEN-LAST:event_jPanelDasboardAdminMouseClicked

    private void jPanelCustomerAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustomerAdminMouseClicked
        // TODO add your handling code here:
        System.out.println("Panel Customer");
        jPanelMainAdmin.removeAll();
        jPanelMainAdmin.repaint();
        jPanelMainAdmin.add(new PanelCustomer());
        jPanelMainAdmin.revalidate();

    }//GEN-LAST:event_jPanelCustomerAdminMouseClicked

    private void jPanelUserAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelUserAdminMouseClicked
        // TODO add your handling code here:
        System.out.println("Panel User");
        PanelUser pu = new PanelUser();
        jPanelMainAdmin.removeAll();
        jPanelMainAdmin.repaint();
        pu.DataDiterima(id_user);
        jPanelMainAdmin.add(pu);
        jPanelMainAdmin.revalidate();
        

    }//GEN-LAST:event_jPanelUserAdminMouseClicked

    private void jPanelServiceAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelServiceAdminMouseClicked
        // TODO add your handling code here:
        System.out.println("Panel Service");
        jPanelMainAdmin.removeAll();
        jPanelMainAdmin.repaint();
        jPanelMainAdmin.add(new PanelOrderService());
        jPanelMainAdmin.revalidate();
    }//GEN-LAST:event_jPanelServiceAdminMouseClicked

    private void jPanelTransaksiAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTransaksiAdminMouseClicked
        jPanelMainAdmin.removeAll();
        jPanelMainAdmin.repaint();
        jPanelMainAdmin.add(new PanelTransaksiMain());
        jPanelMainAdmin.revalidate();
    }//GEN-LAST:event_jPanelTransaksiAdminMouseClicked

    private void jPanelHsLogout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHsLogout1MouseClicked
        // TODO add your handling code here:
        new LOGIN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelHsLogout1MouseClicked

    private void jPanelHsLogout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHsLogout1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelHsLogout1MouseEntered

    private void jPanelHsLogout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHsLogout1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelHsLogout1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            FlatLightLaf.setup();
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelrole;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelCustomerAdmin;
    private javax.swing.JPanel jPanelDasboardAdmin;
    private javax.swing.JPanel jPanelHsLogout1;
    private javax.swing.JPanel jPanelMainAdmin;
    private javax.swing.JPanel jPanelServiceAdmin;
    private javax.swing.JPanel jPanelTransaksiAdmin;
    private javax.swing.JPanel jPanelUserAdmin;
    // End of variables declaration//GEN-END:variables
}
