/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.testing_uas;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.swing.JOptionPane;

/**
 *
 * @author RICKY
 */
public class InputKeluhan extends javax.swing.JDialog {

    /**
     * Creates new form InputKeluhan
     */
    public InputKeluhan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbJudul = new javax.swing.JLabel();
        tfservice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfdesk = new javax.swing.JTextArea();
        jToggleButton2 = new javax.swing.JToggleButton();
        btnInput = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Service :");

        lbJudul.setText("INPUT SERVICE");

        tfservice.setColumns(20);

        jLabel3.setText("Deskripsi :");

        tfdesk.setColumns(20);
        tfdesk.setRows(5);
        jScrollPane1.setViewportView(tfdesk);

        jToggleButton2.setText("RESET");

        btnInput.setText("INSERT");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(tfservice)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lbJudul)))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(btnInput)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton2)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfservice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(btnInput))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        if(btnInput.getText().equals("UPDATE")){
            System.out.println("Database Connected");
            try {
                 String sql = "UPDATE data_service SET service_tambahan = ?, deskripsi = ? WHERE id_data_service = ?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, tfservice.getText());
                ps.setString(2, tfdesk.getText());
                ps.setInt(3, id_service);
                int hasil = ps.executeUpdate();

                if(hasil > 0 && hasil > 0){
                    JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
                }else{
                    JOptionPane.showMessageDialog(null, "Data gagal diupdate");
                }

                this.dispose();
            } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());
            }
        }else if(btnInput.getText().equals("INSERT")){
            try{
                String sql = "INSERT INTO data_service (id_detail_barang, service_tambahan, deskripsi, HistoryKeluhan, price) VALUES (?, ?, ?, ?, ?)";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1,id_detail_barang);
                ps.setString(2, tfservice.getText());
                ps.setString(3, tfdesk.getText());
                ps.setString(4, LocalDateTime.now().toString());
                ps.setString(5, null);
                int hasil=ps.executeUpdate();
                if(hasil==1){
                    System.out.println("Data berhasil ditambahkan");
                    JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan");
                    this.dispose();
                }else{
                    System.out.println("Data gagal ditambahkan");
                }

            }catch(Exception ex){
                ex.printStackTrace();
                System.out.println(ex.getMessage());
                System.out.println("Data gagal ditambahkan");
            }

        }

    }//GEN-LAST:event_btnInputActionPerformed

    private Connection con = Database.getConnection();
    public void GantiNama(int ganti){
        if(ganti==1){
            lbJudul.setText("UPDATE KELUHAN");
            btnInput.setText("UPDATE");
        }else if(ganti==2){
            btnInput.setText("INSERT");
            lbJudul.setText("INSERT KELUHAN");
        }else{
            System.out.println("Tidak ada aksi");
        }
    }



    private int id_detail_barang;
    public void DataDiterima(int id_detail_barang){
        this.id_detail_barang=id_detail_barang;
    }

    private int id_service;
    private String service_tambahan;
    private String desk;
    private String history;
    private int harga;
    public void DataDiterima2(int id_service,int id_detail_barang,String service_tambahan,String desk,String history,int harga){
        System.out.println(id_service);
        System.out.println(id_detail_barang);
        System.out.println(service_tambahan);
        System.out.println(desk);
        System.out.println(history);
        System.out.println(harga);
        this.id_service=id_service;
        this.id_detail_barang=id_detail_barang;
        this.service_tambahan=service_tambahan;
        this.desk=desk;
        this.history=history;
        this.harga=harga;
        tfservice.setText(service_tambahan);
        tfdesk.setText(desk);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputKeluhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputKeluhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputKeluhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputKeluhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InputKeluhan dialog = new InputKeluhan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lbJudul;
    private javax.swing.JTextArea tfdesk;
    private javax.swing.JTextField tfservice;
    // End of variables declaration//GEN-END:variables
}
