/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.testing_uas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RICKY
 */
public class ManageSparepart extends javax.swing.JDialog {

    /**
     * Creates new form ManageSparepart
     */
    public ManageSparepart(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tbSparepart.setModel(model);
        loadKolom();
        TampilSparepart();
    }

    private DefaultTableModel model = new DefaultTableModel();
    private Connection con = Database.getConnection();
    private ArrayList<Sparepart> listSpareparts = new ArrayList<>();

    private int id_data_service1;
    public void DataDiterima(int id_data_service){
        this.id_data_service1=id_data_service;
        System.out.println(id_data_service);

        loadSparepart();
    }
    public void refres(){
        System.out.println("refres dijalankan");
        model.setRowCount(0);
        listSpareparts.clear();
        loadSparepart();
        TampilSparepart();

    }

    public void loadKolom(){
        model.addColumn("Nama Sparepart");
        model.addColumn("harga");
    }

    public void TampilSparepart(){
        model.setRowCount(0);
        for(Sparepart b : listSpareparts){
            model.addRow(new Object[]{
                b.getNama(),
                b.getHarga()
            });
        }
    }

    public void loadSparepart(){
        System.out.println("Load sparepart dijalankan");
        if(con != null){
            System.out.println("Koneksi terhubung");
            String sql = "SELECT * FROM detail_sperpart where id_data_service = ?";
            try{
                System.out.println("try catch dijalankan");
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1, id_data_service1);
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    int id_sperpart = rs.getInt("id_sperpart");
                    int id_service = rs.getInt("id_data_service");
                    String namakel = rs.getString("nama_sperpart");
                    double hargakel = rs.getDouble("harga_sperpart");
                    System.out.println(namakel+hargakel);
                    Sparepart sparepart = new Sparepart(id_sperpart,id_service, namakel, hargakel);

                    //masukan ke arraylist
                    listSpareparts.add(sparepart);
                }
                rs.close();
                ps.close();
                TampilSparepart();
            }catch(Exception e){
                System.out.println("Error : "+e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbSparepart = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbSparepart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbSparepart);

        jLabel1.setText("SPAREPART YANG DI BUTUHKAN");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(210, 210, 210)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        InputSparepart is = new InputSparepart(null, true);
        is.DataDiterima(id_data_service1);
        is.GantiNama(2);
        is.setVisible(true);
        refres();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int baristerpilih = tbSparepart.getSelectedRow();
        int id = listSpareparts.get(baristerpilih).getId_sperpart();
        int service = listSpareparts.get(baristerpilih).getId_data_service();
        String nama = listSpareparts.get(baristerpilih).getNama();
        Double harga = listSpareparts.get(baristerpilih).getHarga();

        InputSparepart is = new InputSparepart(null, true);
        is.DataDiterima2(id,service,nama,harga);
        is.GantiNama(1);
        is.setVisible(true);
        refres();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int baristerpilih = tbSparepart.getSelectedRow();
        int id = listSpareparts.get(baristerpilih).getId_sperpart();
        int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            try{
                String sql = "DELETE FROM detail_sperpart WHERE id_sperpart = ?";
                PreparedStatement state = con.prepareStatement(sql);
                state.setInt(1, id);
                state.executeUpdate();
                state.close();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                refres();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Data gagal dihapus");
                e.printStackTrace();
            }
        }
        refres();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageSparepart dialog = new ManageSparepart(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSparepart;
    // End of variables declaration//GEN-END:variables
}
class Sparepart{

    private int id_sperpart;
    private int id_data_service;
    private String nama;
    private double harga;
    public Sparepart(int id_sperpart, int id_data_service, String nama, double harga){
        this.id_sperpart=id_sperpart;
        this.id_data_service=id_data_service;
        this.harga=harga;
        this.nama=nama;
    }
    
    public void setHarga(double harga) {
        this.harga = harga;
    }
    public void setId_data_service(int id_data_service) {
        this.id_data_service = id_data_service;
    }
    public void setId_sperpart(int id_sperpart) {
        this.id_sperpart = id_sperpart;
    }
    public void setNama(String nama) {
        this.nama = nama;
    }
    public double getHarga() {
        return harga;
    }
    public int getId_data_service() {
        return id_data_service;
    }
    public int getId_sperpart() {
        return id_sperpart;
    }
    public String getNama() {
        return nama;
    }
}
