/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.testing_uas;


import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.security.*;
import java.sql.ResultSet;

/**
 *
 * @author FA506
 */
public class UserUpdate extends javax.swing.JDialog {

    /**
     * Creates new form UserUpdate
     */
    public UserUpdate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUpdate = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jComboBoxUwU = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jLabel4.setText("Nama");

        jLabel5.setText("Role");

        jComboBoxUwU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Role", "admin", "staff" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldUsername)
                    .addComponent(jTextFieldPassword)
                    .addComponent(jTextFieldNama)
                    .addComponent(jComboBoxUwU, 0, 162, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUwU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jLabel1.setText("USER UPDATE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClose)
                        .addGap(39, 39, 39))))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Connection con = Database.getConnection();
    private int id_user;

    public void DataDiTerima(int id_user, String username, String password, String nama, String role) {
        this.id_user = id_user;
        jTextFieldUsername.setText(username);
        jTextFieldPassword.setText(password);
        jTextFieldNama.setText(nama);
        jComboBoxUwU.setSelectedItem(role);
    }
    private int ganti;
    public void GantiNama(int ganti){
        if(ganti == 1){
            jLabel1.setText("USER UPDATE");
            jButtonUpdate.setText("UPDATE");
        }else if(ganti == 2){
            jLabel1.setText("USER INSERT");
            jButtonUpdate.setText("INSERT");
        }
    }
    


    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        if(jButtonUpdate.getText().equals("UPDATE")){
    
            try {
                String sql = "UPDATE user SET username=?, password=?, nama=?, role=? WHERE id_user=?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, jTextFieldUsername.getText());
                ps.setString(2, jTextFieldPassword.getText());
                ps.setString(3, jTextFieldNama.getText());
                ps.setString(4, jComboBoxUwU.getSelectedItem().toString());
                ps.setInt(5, id_user);
                // check apakah username sudah ada
                String sql2 = "SELECT * FROM user WHERE username=?";
                PreparedStatement ps2 = con.prepareStatement(sql2);
                ps2.setString(1, jTextFieldUsername.getText());
                if(ps2.executeQuery().next()){
                    JOptionPane.showMessageDialog(this, "Username sudah ada");
                    return;
                }else{
                    // jika inputan kosong
                    if(jComboBoxUwU.getSelectedItem().toString().equals("Pilih Role") || jTextFieldNama.getText().equals("") || jTextFieldPassword.getText().equals("") || jTextFieldUsername.getText().equals("")){
                        JOptionPane.showMessageDialog(this, "Pilih role atau inputan kosong");
                        return;
                    }else{
                        int hasil = ps.executeUpdate();
                        if (hasil > 0) {
                            JOptionPane.showMessageDialog(this, "Data berhasil diupdate");
                            this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(this, "Data gagal diupdate");
                            System.out.println("Error: Data gagal diupdate");
                        }
                    }
                    System.out.println("Username belum ada");
                }
                
            this.dispose();
            } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());
            }
        }else if(jButtonUpdate.getText().equals("INSERT")){
            try {
                String sql = "INSERT INTO user (username, password, nama, role) VALUES (?,?,?,?)";
                MessageDigest md = MessageDigest.getInstance("MD5");
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, jTextFieldUsername.getText());
                ps.setString(2, jTextFieldPassword.getText());
                ps.setString(3, jTextFieldNama.getText());
                ps.setString(4, jComboBoxUwU.getSelectedItem().toString());
                // check apakah username sudah ada
                String sql2 = "SELECT * FROM user WHERE username=?";
                PreparedStatement ps2 = con.prepareStatement(sql2);
                ps2.setString(1, jTextFieldUsername.getText());
                if(ps2.executeQuery().next()){
                    JOptionPane.showMessageDialog(this, "Username sudah ada");
                    return;
                }else{
                    //jika role yang dipilih selain admin dan staff
                    if(jComboBoxUwU.getSelectedItem().toString().equals("Pilih Role") || jTextFieldNama.getText().equals("") || jTextFieldPassword.getText().equals("") || jTextFieldUsername.getText().equals("")){
                        JOptionPane.showMessageDialog(this, "Pilih role / inputan kosong");
                        return;
                    }else if(jComboBoxUwU.getSelectedItem().toString().equals("admin") || jComboBoxUwU.getSelectedItem().toString().equals("staff")){
                        int hasil = ps.executeUpdate();
                        if (hasil > 0) {
                            JOptionPane.showMessageDialog(this, "Data berhasil diinsert");
                            this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(this, "Data gagal diinsert");
                            System.out.println("username: " + jTextFieldUsername.getText());
                            System.out.println("password: " + md.digest(jTextFieldPassword.getText().getBytes()).toString());
                            System.out.println("nama: " + jTextFieldNama.getText());
                            System.out.println("role: " + jComboBoxUwU.getSelectedItem().toString());
                            System.out.println("Error: Data gagal diinsert");
                        }
                    }
                    System.out.println("Username belum ada");
                }
                
            this.dispose();
            } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());
            }
        }
            
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
            this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserUpdate dialog = new UserUpdate(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxUwU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
